export const ASIA_REGIONS = {
  Vietnam: [
    'Ho Chi Minh City',
    'Hanoi',
    'Da Nang',
    'Da Lat',
    'Vung Tau',
    'Nha Trang',
    'Phu Quoc',
    'Hoi An',
    'Hue',
  ],
  Thailand: [
    'Bangkok',
    'Phuket',
    'Chiang Mai',
    'Pattaya',
    'Koh Samui',
    'Hua Hin',
    'Krabi',
    'Ayutthaya',
  ],
  Singapore: ['Marina Bay', 'Sentosa', 'Orchard', 'Changi', 'Bugis', 'Clarke Quay'],
  Malaysia: [
    'Kuala Lumpur',
    'Penang',
    'Langkawi',
    'Malacca',
    'Johor Bahru',
    'Kota Kinabalu',
    'Ipoh',
  ],
  Indonesia: ['Bali', 'Jakarta', 'Yogyakarta', 'Bandung', 'Surabaya', 'Lombok'],
  Philippines: ['Manila', 'Cebu', 'Boracay', 'Palawan', 'Bohol', 'Davao', 'Makati'],
  Cambodia: ['Siem Reap', 'Phnom Penh', 'Sihanoukville', 'Kampot', 'Kep'],
  Laos: ['Luang Prabang', 'Vientiane', 'Vang Vieng', 'Pakse'],
  Brunei: ['Bandar Seri Begawan', 'Jerudong', 'Kuala Belait'],
  Japan: [
    'Tokyo',
    'Osaka',
    'Kyoto',
    'Hokkaido',
    'Okinawa',
    'Fukuoka',
    'Nagoya',
    'Hiroshima',
    'Nara',
  ],
  'South Korea': ['Seoul', 'Busan', 'Jeju', 'Incheon', 'Gyeongju', 'Daegu', 'Suwon'],
  Taiwan: ['Taipei', 'Kaohsiung', 'Taichung', 'Tainan', 'Hualien', 'Jiufen'],
  China: ['Beijing', 'Shanghai', 'Guangzhou', 'Shenzhen', 'Chengdu', "Xi'an", 'Hangzhou', 'Sanya'],
  'Hong Kong': ['Central', 'Kowloon', 'Lantau', 'Tsim Sha Tsui', 'Causeway Bay', 'Mong Kok'],
  Macau: ['Cotai', 'Macau Peninsula', 'Taipa', 'Coloane'],
};

// This transforms the object into an array so Angular's *ngFor can loop through it easily!
export const REGION_LIST = Object.keys(ASIA_REGIONS).map((country) => ({
  countryName: country,
  cities: ASIA_REGIONS[country as keyof typeof ASIA_REGIONS],
}));
